### ISSUE TITLE
Component is not found in path ？

### ISSUE THREAD

**Issue by starriv** [meili/min-cli#21]
Platform：
使用的操作系统: macOS 10.13.1
Min Cli 的版本: 1.0.3
Node 版本 v8.4.0
---------------------------
是我姿势不对吗？
<img width="775" alt="qq20171120-171623 2x" src="https://user-images.githubusercontent.com/7098001/33010785-bf28e2b2-ce16-11e7-8544-39b1d69b11c9.png">

**Comment by starriv** [comment]
```

**Comment by min-team** [comment]
@starriv 提供下小程序项目下 min.config.json 文件的配置信息

**Comment by Genuifx** [comment]
你的路径错误了，应该是`./package/@minui/wxc-dialog`

**Comment by starriv** [comment]
```json
{
  "navigationBarTitleText": "我的",
  "usingComponents": {
    "wxc-dialog": "./dist/package/@minui/wxc-dialog"
  }
}
```

**Comment by min-team** [comment]
@starriv wxc-dialog 提供自定义标签的文件路径要指向到组件编译后的路径，改成这样试试：
my.json
{
  "navigationBarTitleText": "我的",
  "usingComponents": {
    "wxc-dialog": "./dist/packages/@minui/wxc-dialog/dist/index"
  }
}

**Comment by min-team** [comment]
@starriv wxc-dialog 提供自定义标签的文件路径要指向到组件编译后的路径，改成这样试试：
my.json
``` json
{
"navigationBarTitleText": "我的",
"usingComponents": {
"wxc-dialog": "./dist/packages/dist/index"
}
}
``` json

**Comment by min-team** [comment]
@starriv wxc-dialog 提供自定义标签的文件路径要指向到组件编译后的路径，改成这样试试：
my.json
``` json
{
"navigationBarTitleText": "我的",
"usingComponents": {
"wxc-dialog": "./dist/packages/dist/index"
}
}
```

**Comment by min-team** [comment]
@starriv wxc-dialog 提供自定义标签的文件路径要指向到组件编译后的路径，改成这样试试：
my.json

{
    "navigationBarTitleText": "我的",
    "usingComponents": {
        "wxc-dialog": "./dist/packages/@minui/wxc-dialog/dist/index"
    }
}

**Comment by min-team** [comment]
@starriv wxc-dialog 提供自定义标签的文件路径要指向到组件编译后的路径，改成这样试试：
my.json
``` json
{
  "navigationBarTitleText": "我的",
  "usingComponents": {
    "wxc-dialog": "./dist/packages/@minui/wxc-dialog/dist/index"
  }
}
```

**Comment by starriv** [comment]
有错的样子
```
exparserScriptError
Expect FLOW_CREATE_NODE but get another
Error: Expect FLOW_CREATE_NODE but get another
    at e.value (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:14:53)
    at http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:14:334
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:14:306)
    at e.value (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:13:29213)
    at Object.p.create [as createElement] (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:3:16657)
    at e.value (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:13:31558)
    at http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:14:334
    at Array.forEach (<anonymous>)
    at e.value (http://127.0.0.1:9973/__pageframe__/__dev__/WAWebview.js:14:306)
```

**Comment by lb491798689** [comment]
这路径确实有问题，改了路径，命名文件是存在的，但是一直提示这个问题
