### ISSUE TITLE
在 MinUI 根目录下执行 `$ min dev`，生成 dist/ 目录 出现错误 

### ISSUE THREAD

**Issue by ap310** [meili/min-cli#4]
在 MinUI 根目录下执行 `$ min dev`，生成 dist/ 目录 出现错误 
C:\Users\Administrator\AppData\Roaming\npm\node_modules\@mindev\min-cli\lib\util\beautify.js:4
const { js_beautify, html_beautify, css_beautify } = beautify;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@mindev\min-cli\lib\util\index.js:3:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by min-team** [comment]
@ap310 尝试升级node版本试试，不过目前windows系统还存在生成页面路径问题，Min Cli下个版本将会修复

**Comment by LancelotLewis** [comment]
@min-team 下个版本啥时候出？

**Comment by sonicsunsky** [comment]
win10系统，最新版本nodejs, 安装min-cli环境可以但是初始化min-cli时提示错误:
执行min init命令错误:
? 请设置项目目录 E:\wx_app_projects\git_repo\wx-minCli
? 请选择项目类型 新建小程序
? 是否继续高级设置 Yes
? 请设置项目标题 MinUI
? 请设置项目描述
? 是否使用全局变量 Yes
? 是否使用全局模板 Yes
? 请设置项目打包保存路径 dist
? 请设置 git repository 地址
? 请设置 author
[15:39:44] [创建] 项目 "E:\wx_app_projects\git_repo\wx-minCli"
[15:39:44] [拷贝] LICENSE
[15:39:44] [拷贝] min.config.json
[15:39:44] [拷贝] package.json
[15:39:44] [拷贝] README.md
[15:39:44] [拷贝] src
[15:39:44] [拷贝] src/app.wxa
[15:39:44] [拷贝] src/common
[15:39:44] [拷贝] src/common/layout
[15:39:44] [拷贝] src/common/layout/foot.wxc
[15:39:44] [拷贝] src/common/layout/head.wxc
[15:39:44] [拷贝] src/pages
[15:39:44] [拷贝] src/pages/home
[15:39:44] [拷贝] src/pages/home/index.wxp
[15:39:44] [执行] 命令：npm install
[15:39:44] [信息] 安装中, 请耐心等待...
{ Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ] }

折腾半天了，还没弄好，求助大神们，还有min-init 操作的时候没有详细的步骤说明;

**Comment by min-team** [comment]
@ap310 运行 `min dev`遇到问题解决了么，目前 Min Cli 已更新到v1.0.3版本，如存在问题请升级node和 min cli到最新版本再试
