### ISSUE TITLE
执行min init指令错误 spawn npm ENOENT

### ISSUE THREAD

**Issue by sonicsunsky** [meili/min-cli#5]
win10系统，最新版本nodejs, 安装min-cli环境可以但是初始化min-cli时提示错误:
执行min init命令错误:
? 请设置项目目录 E:\wx_app_projects\git_repo\wx-minCli
? 请选择项目类型 新建小程序
? 是否继续高级设置 Yes
? 请设置项目标题 MinUI
? 请设置项目描述
? 是否使用全局变量 Yes
? 是否使用全局模板 Yes
? 请设置项目打包保存路径 dist
? 请设置 git repository 地址
? 请设置 author
[15:39:44] [创建] 项目 "E:\wx_app_projects\git_repo\wx-minCli"
[15:39:44] [拷贝] LICENSE
[15:39:44] [拷贝] min.config.json
[15:39:44] [拷贝] package.json
[15:39:44] [拷贝] README.md
[15:39:44] [拷贝] src
[15:39:44] [拷贝] src/app.wxa
[15:39:44] [拷贝] src/common
[15:39:44] [拷贝] src/common/layout
[15:39:44] [拷贝] src/common/layout/foot.wxc
[15:39:44] [拷贝] src/common/layout/head.wxc
[15:39:44] [拷贝] src/pages
[15:39:44] [拷贝] src/pages/home
[15:39:44] [拷贝] src/pages/home/index.wxp
[15:39:44] [执行] 命令：npm install
[15:39:44] [信息] 安装中, 请耐心等待...
{ Error: spawn npm ENOENT
at _errnoException (util.js:1024:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn npm',
path: 'npm',
spawnargs: [ 'install' ] }

折腾半天了，还没弄好，求助大神们，另外还有min-init 操作的时候没有详细的步骤说明;

**Comment by sonicsunsky** [comment]
? 请设置项目目录 E:\wx_app_projects\git_repo\wx-minCli
? 请选择项目类型 新建小程序
? 是否继续高级设置 Yes
? 请设置项目标题 MinUI
? 请设置项目描述
? 是否使用全局变量 Yes
? 是否使用全局模板 Yes
? 请设置项目打包保存路径 dist
? 请设置 git repository 地址
? 请设置 author

这些官方都没有给出解释和说明，小白表示看不懂啊

**Comment by sonicsunsky** [comment]
这个min-cli安装失败，初始化失败，生成目录失败等问题官方都没有给出一些常用的解决方案，网上根本就找不到类似的解决办法，求助官方大神们

**Comment by min-team** [comment]
@sonicsunsky windows下的问题我们一直在关注，正在火速修复中，Min Cli下个版本会在明天发布上线

**Comment by LancelotLewis** [comment]
@min-team 一直在等你们更新了再开发

**Comment by min-team** [comment]
@sonicsunsky @LancelotLewis 久等了，windows系统下的初始化项目，安装组件，生成项目路径等问题已在1.0.2版本修复，请将Min Cli升级到最新版再试，感谢支持🙏
