### ISSUE TITLE
min install @minui/wxc-loading 提示错误spawn npm ENOENT

### ISSUE THREAD

**Issue by sonicsunsky** [meili/min-cli#6]
min install @minui/wxc-loading
{ Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '@minui/wxc-loading', '--save' ] }

**Comment by sonicsunsky** [comment]
现有小程序项目添加minui里的自定义组件min install @minui/wxc-loading 报错

**Comment by sonicsunsky** [comment]
min init
? 请设置项目目录 E:\wx_app_projects\git_repo\wx-minui\minui\
? 请选择项目类型 新建组件库
? 是否继续高级设置 No
[09:44:17] [创建] 项目 "E:\wx_app_projects\git_repo\wx-minui\minui\"
[09:44:17] [拷贝] LICENSE
[09:44:17] [拷贝] min.config.json
[09:44:17] [拷贝] package.json
[09:44:17] [拷贝] README.md
[09:44:17] [拷贝] src
[09:44:17] [拷贝] src/app.wxa
[09:44:17] [拷贝] src/common
[09:44:17] [拷贝] src/common/layout
[09:44:17] [拷贝] src/common/layout/foot.wxc
[09:44:17] [拷贝] src/common/layout/head.wxc
[09:44:17] [拷贝] src/pages
[09:44:17] [拷贝] src/pages/home
[09:44:17] [拷贝] src/pages/home/index.wxp
[09:44:17] [执行] 命令：npm install
[09:44:17] [信息] 安装中, 请耐心等待...
{ Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ] }

**Comment by sonicsunsky** [comment]
什么时候能修复好呀?

**Comment by min-team** [comment]
@sonicsunsky 该问题会在今天修复好

**Comment by min-team** [comment]
@sonicsunsky 在现有小程序项目上添加minui组件，运行min instal报错问题已修复，请更新Min Cli到1.0.2版本再试
